version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notino_app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - shared_network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

networks:
  shared_network:
    external: true

