# Use the official MySQL image
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD="newpassword"
ENV MYSQL_DATABASE=notino
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD="newpassword"

# Copy initial database scripts to the container
COPY DBs /docker-entrypoint-initdb.d/
